name: Continuous integration example

on: 
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
        cache: 'maven' # Opcional: Acelera las builds futuras cacheando las dependencias

    - name: Generate tag
      run: echo "tag=$(mvn -q help:evaluate -Dexpression=project.version -DforceStdout)" > $GITHUB_OUTPUT
      id: project
    - name: Generate Docker image
      # Si tu pom.xml está en una subcarpeta (ej. /backend), descomenta la siguiente línea:
      # working-directory: ./ruta-a-tu-carpeta
      run: mvn spring-boot:build-image -DskipTests -Dspring-boot.build-image.imageName=${{ secrets.DOCKERHUB_USERNAME }}/posts:${{steps.project.outputs.tag}}
      
    - name: Login to DockerHub
      run: docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" -p "${{ secrets.DOCKERHUB_TOKEN }}"
      
    - name: Push image to DockerHub
      # Corregido: Debe coincidir exactamente con el imageName del paso de Maven
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/posts:${{steps.project.outputs.tag}}