name: Unit and Integration Tests

on:
  push:
    branches-ignore:
      - main
    paths:
      - 'src/**'
      - 'pom.xml'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run Unit Tests
        run: mvn test -Dtest="*Test" -DskipITs

      - name: Run Integration Tests
        run: mvn integration-test -DskipTests
